We are going to read in a CSV that has observations of canopy height at periodic times.  The times are indicated by days after the start of the planting, but we can do more it is a real date, so lets convert to a date. 

In [2]:
import pandas as pd
import arrow

In [15]:
cn_df = pd.read_csv('/volumes/Curt-MacPro-Backup/D3M/terra/Raw-data/raw_data/terra_tabular/s4_canopy_height_formatted.csv')

In [16]:
cn_df.head()

cultivar                                       sitename  day  canopy_height
0  PI329569   MAC Field Scanner Season 4 Range 26 Column 8  133            364
1  PI152923   MAC Field Scanner Season 4 Range 26 Column 9  133            359
2  PI152923  MAC Field Scanner Season 4 Range 26 Column 10  133            366
3  PI330803  MAC Field Scanner Season 4 Range 26 Column 13  133            367
4  PI330803  MAC Field Scanner Season 4 Range 26 Column 14  133            368

pretend we are starting at the beginning of 2013.  Action:  Find the actual first day of planting seaston #4

In [17]:
startdate = arrow.get("2013-03-01T01:31:51.601000+00:00")

In [18]:
print(len(cn_df))

35510


In [19]:
startdate

<Arrow [2013-03-01T01:31:51.601000+00:00]>

In [20]:
startdate.shift(days=1)

<Arrow [2013-03-02T01:31:51.601000+00:00]>

In [33]:
import itertools
count = 0
def convertDayToDate(startdate,dayOffset):
    return startdate.shift(days=int(dayOffset))

cn_df['date'] = startdate
    
for i in range(len(cn_df)):
    cn_df['date'][i] = convertDayToDate(startdate,cn_df['day'][i])
    count += 1
    if (count % 5000) == 0:
        print(count)

/Users/curtislisle/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


5000
10000
15000
20000
25000
30000
35000


In [34]:
cn_df['date']

0        2013-07-12T01:31:51.601000+00:00
1        2013-07-12T01:31:51.601000+00:00
2        2013-07-12T01:31:51.601000+00:00
3        2013-07-12T01:31:51.601000+00:00
4        2013-07-12T01:31:51.601000+00:00
5        2013-07-12T01:31:51.601000+00:00
6        2013-07-12T01:31:51.601000+00:00
7        2013-07-12T01:31:51.601000+00:00
8        2013-07-12T01:31:51.601000+00:00
9        2013-07-12T01:31:51.601000+00:00
10       2013-07-12T01:31:51.601000+00:00
11       2013-07-12T01:31:51.601000+00:00
12       2013-07-12T01:31:51.601000+00:00
13       2013-07-12T01:31:51.601000+00:00
14       2013-07-12T01:31:51.601000+00:00
15       2013-07-12T01:31:51.601000+00:00
16       2013-07-12T01:31:51.601000+00:00
17       2013-07-12T01:31:51.601000+00:00
18       2013-07-12T01:31:51.601000+00:00
19       2013-07-12T01:31:51.601000+00:00
20       2013-07-12T01:31:51.601000+00:00
21       2013-07-12T01:31:51.601000+00:00
22       2013-07-12T01:31:51.601000+00:00
23       2013-07-12T01:31:51.60100

In [35]:
cn_df.head()

cultivar                                       sitename  day  \
0  PI329569   MAC Field Scanner Season 4 Range 26 Column 8  133   
1  PI152923   MAC Field Scanner Season 4 Range 26 Column 9  133   
2  PI152923  MAC Field Scanner Season 4 Range 26 Column 10  133   
3  PI330803  MAC Field Scanner Season 4 Range 26 Column 13  133   
4  PI330803  MAC Field Scanner Season 4 Range 26 Column 14  133   

   canopy_height                              date  
0            364  2013-07-12T01:31:51.601000+00:00  
1            359  2013-07-12T01:31:51.601000+00:00  
2            366  2013-07-12T01:31:51.601000+00:00  
3            367  2013-07-12T01:31:51.601000+00:00  
4            368  2013-07-12T01:31:51.601000+00:00

In [36]:
cn_df[1:50]

cultivar                                       sitename  day  \
1   PI152923   MAC Field Scanner Season 4 Range 26 Column 9  133   
2   PI152923  MAC Field Scanner Season 4 Range 26 Column 10  133   
3   PI330803  MAC Field Scanner Season 4 Range 26 Column 13  133   
4   PI330803  MAC Field Scanner Season 4 Range 26 Column 14  133   
5   PI585454  MAC Field Scanner Season 4 Range 26 Column 15  133   
6        NaN   MAC Field Scanner Season 4 Range 27 Column 2  133   
7   PI641807   MAC Field Scanner Season 4 Range 27 Column 3  133   
8   PI641835   MAC Field Scanner Season 4 Range 27 Column 8  133   
9   PI170787   MAC Field Scanner Season 4 Range 27 Column 9  133   
10  PI145619  MAC Field Scanner Season 4 Range 27 Column 11  133   
11  PI145619  MAC Field Scanner Season 4 Range 27 Column 12  133   
12  PI562990   MAC Field Scanner Season 4 Range 28 Column 6  133   
13  PI586541   MAC Field Scanner Season 4 Range 28 Column 9  133   
14  PI585467  MAC Field Scanner Season 4 Range 28 Column 11  133   
15  PI221651  MAC Field Scanner Season 4 Range 28 Column 14  133   
16  PI152816   MAC Field Scanner Season 4 Range 29 Column 3  133   
17  PI152816   MAC Field Scanner Season 4 Range 29 Column 4  133   
18  PI641824  MAC Field Scanner Season 4 Range 29 Column 14  133   
19  PI641807  MAC Field Scanner Season 4 Range 29 Column 15  133   
20  PI329614   MAC Field Scanner Season 4 Range 31 Column 7  133   
21  PI570109   MAC Field Scanner Season 4 Range 31 Column 9  133   
22   PI63715  MAC Field Scanner Season 4 Range 31 Column 11  133   
23   PI63715  MAC Field Scanner Season 4 Range 31 Column 12  133   
24  PI329506  MAC Field Scanner Season 4 Range 31 Column 14  133   
25  PI641821  MAC Field Scanner Season 4 Range 31 Column 15  133   
26       NaN   MAC Field Scanner Season 4 Range 32 Column 2  133   
27  PI330199   MAC Field Scanner Season 4 Range 32 Column 6  133   
28  PI563330   MAC Field Scanner Season 4 Range 32 Column 7  133   
29  PI563330   MAC Field Scanner Season 4 Range 32 Column 8  133   
30  PI329673   MAC Field Scanner Season 4 Range 32 Column 9  133   
31  PI329673  MAC Field Scanner Season 4 Range 32 Column 10  133   
32  PI329394  MAC Field Scanner Season 4 Range 32 Column 14  133   
33  PI455301  MAC Field Scanner Season 4 Range 32 Column 15  133   
34       NaN   MAC Field Scanner Season 4 Range 33 Column 2  133   
35  PI562971   MAC Field Scanner Season 4 Range 33 Column 7  133   
36  PI562971   MAC Field Scanner Season 4 Range 33 Column 8  133   
37  PI655981   MAC Field Scanner Season 4 Range 33 Column 9  133   
38  PI641810  MAC Field Scanner Season 4 Range 33 Column 11  133   
39  PI569443  MAC Field Scanner Season 4 Range 33 Column 13  133   
40  PI569443  MAC Field Scanner Season 4 Range 33 Column 14  133   
41  PI585461   MAC Field Scanner Season 4 Range 34 Column 5  133   
42  PI533998   MAC Field Scanner Season 4 Range 12 Column 3  111   
43  PI655983   MAC Field Scanner Season 4 Range 12 Column 7  111   
44  PI181080   MAC Field Scanner Season 4 Range 12 Column 9  111   
45  PI181080  MAC Field Scanner Season 4 Range 12 Column 10  111   
46  PI221548  MAC Field Scanner Season 4 Range 12 Column 12  111   
47  PI213900  MAC Field Scanner Season 4 Range 12 Column 13  111   
48  PI213900  MAC Field Scanner Season 4 Range 12 Column 14  111   
49       NaN   MAC Field Scanner Season 4 Range 13 Column 2  111   

    canopy_height                              date  
1             359  2013-07-12T01:31:51.601000+00:00  
2             366  2013-07-12T01:31:51.601000+00:00  
3             367  2013-07-12T01:31:51.601000+00:00  
4             368  2013-07-12T01:31:51.601000+00:00  
5             360  2013-07-12T01:31:51.601000+00:00  
6             349  2013-07-12T01:31:51.601000+00:00  
7             328  2013-07-12T01:31:51.601000+00:00  
8             392  2013-07-12T01:31:51.601000+00:00  
9             340  2013-07-12T01:31:51.601000+00:00  
10            341  2013-07-12T01:31:51.601000+00:00  
11       

In [38]:
cn_df.to_csv('/volumes/Curt-MacPro-Backup/D3M/terra/processing/tabular/s4_canopy_height_pseudo_time_v1.csv')

Now look at splitting out the row and column as additional independent variables by picking them out of the sitename

In [42]:
print(cn_df['sitename'][0])
print(cn_df['sitename'][0].split(' ')[4])
print(cn_df['sitename'][0].split(' ')[6])
print(cn_df['sitename'][0].split(' ')[8])

MAC Field Scanner Season 4 Range 26 Column 8
4
26
8


In [45]:

cn_df['range'] = 0
cn_df['column'] = 0
cn_df['season'] = 0
count = 0

# loop through the entire dataframe and add values to the columns according to the sitename contents
for i in range(len(cn_df)):
    cn_df['season'][i] = int(cn_df['sitename'][i].split(' ')[4])
    cn_df['range'][i] = int(cn_df['sitename'][i].split(' ')[6])
    cn_df['column'][i] = int(cn_df['sitename'][i].split(' ')[8])
    count += 1
    if (count % 5000) == 0:
        print(count)

/Users/curtislisle/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
/Users/curtislisle/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/Users/curtislisle/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.


5000
10000
15000
20000
25000
30000
35000


In [46]:
cn_df.head()

cultivar                                       sitename  day  \
0  PI329569   MAC Field Scanner Season 4 Range 26 Column 8  133   
1  PI152923   MAC Field Scanner Season 4 Range 26 Column 9  133   
2  PI152923  MAC Field Scanner Season 4 Range 26 Column 10  133   
3  PI330803  MAC Field Scanner Season 4 Range 26 Column 13  133   
4  PI330803  MAC Field Scanner Season 4 Range 26 Column 14  133   

   canopy_height                              date  range  column  season  
0            364  2013-07-12T01:31:51.601000+00:00     26       8       4  
1            359  2013-07-12T01:31:51.601000+00:00     26       9       4  
2            366  2013-07-12T01:31:51.601000+00:00     26      10       4  
3            367  2013-07-12T01:31:51.601000+00:00     26      13       4  
4            368  2013-07-12T01:31:51.601000+00:00     26      14       4

In [48]:
cn_df.to_csv('/volumes/Curt-MacPro-Backup/D3M/terra/processing/tabular/s4_canopy_height_pseudo_time_v2.csv', index=False)

**give a place to restart by re-loading the dataset**

In [3]:
cn_df = pd.read_csv('/volumes/Curt-MacPro-Backup/D3M/terra/processing/tabular/s4_canopy_height_pseudo_time_v2.csv')

convert the cultivar into a numerical code so a tensor can be made of the dataset for training a neural net

In [4]:
cn_df['cultivar_code'] = cn_df['cultivar'].cat.codes

AttributeError: Can only use .cat accessor with a 'category' dtype

In [5]:
cn_df.dtypes

cultivar         object
sitename         object
day               int64
canopy_height     int64
date             object
range             int64
column            int64
season            int64
dtype: object

In [6]:
unique_counts = pd.DataFrame.from_records([(col, cn_df[col].nunique()) for col in cn_df.columns],
                          columns=['Column_Name', 'Num_Unique']).sort_values(by=['Num_Unique'])

In [7]:
unique_counts

Column_Name  Num_Unique
7         season           1
6         column          14
5          range          52
2            day          68
4           date          68
0       cultivar         269
3  canopy_height         407
1       sitename         715

In [11]:
cn_df['date'] = cn_df['date'].astype('datetime64')

In [13]:
cn_df['cultivar'] = cn_df['cultivar'].astype('category')

In [27]:
cn_df.head()

cultivar                                       sitename  day  \
0  PI329569   MAC Field Scanner Season 4 Range 26 Column 8  133   
1  PI152923   MAC Field Scanner Season 4 Range 26 Column 9  133   
2  PI152923  MAC Field Scanner Season 4 Range 26 Column 10  133   
3  PI330803  MAC Field Scanner Season 4 Range 26 Column 13  133   
4  PI330803  MAC Field Scanner Season 4 Range 26 Column 14  133   

   canopy_height                    date  range  column  season  
0            364 2013-07-12 01:31:51.601     26       8       4  
1            359 2013-07-12 01:31:51.601     26       9       4  
2            366 2013-07-12 01:31:51.601     26      10       4  
3            367 2013-07-12 01:31:51.601     26      13       4  
4            368 2013-07-12 01:31:51.601     26      14       4

In [28]:
# now we convert the "string-ish" values of the categorical variable into their integer indices
cn_df['cultivar'] = cn_df['cultivar'].cat.codes

In [29]:
%%timeit

# do that above when you need to time how long something takes.  It doesn't automatically generate output, though, so you 
# would need to use a print() statement.

cn_df.head()

95.3 µs ± 1.96 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [31]:
cn_df.head()

cultivar                                       sitename  day  \
0        86   MAC Field Scanner Season 4 Range 26 Column 8  133   
1        13   MAC Field Scanner Season 4 Range 26 Column 9  133   
2        13  MAC Field Scanner Season 4 Range 26 Column 10  133   
3       115  MAC Field Scanner Season 4 Range 26 Column 13  133   
4       115  MAC Field Scanner Season 4 Range 26 Column 14  133   

   canopy_height                    date  range  column  season  
0            364 2013-07-12 01:31:51.601     26       8       4  
1            359 2013-07-12 01:31:51.601     26       9       4  
2            366 2013-07-12 01:31:51.601     26      10       4  
3            367 2013-07-12 01:31:51.601     26      13       4  
4            368 2013-07-12 01:31:51.601     26      14       4

In [32]:
# split the inputs and the target feature.  They will stay aligned because of the index value in pandas.
train_df = cn_df[['cultivar','day','range','column','season']]
target_df = cn_df['canopy_height']

In [33]:
train_df.head()

cultivar  day  range  column  season
0        86  133     26       8       4
1        13  133     26       9       4
2        13  133     26      10       4
3       115  133     26      13       4
4       115  133     26      14       4

In [34]:
target_df.head()

0    364
1    359
2    366
3    367
4    368
Name: canopy_height, dtype: int64

In [74]:
import sklearn
from sklearn.model_selection import train_test_split

train_data,test_data = train_test_split(train_df.values)
train_targets,test_targets = train_test_split(target_df.values)
print(train_data.shape,test_data.shape)
print(train_targets.shape,test_targets.shape)


(26632, 5) (8878, 5)
(26632,) (8878,)


In [75]:
train_data = train_df.values
train_targets = target_df.values
print(train_data.shape)
print(train_targets.shape)

(35510, 5)
(35510,)


In [76]:
train_targets[0:10]

array([364, 359, 366, 367, 368, 360, 349, 328, 392, 340])

In [77]:
train_data = train_data.astype('float64')
train_targets = train_targets.astype('float64')
test_data = test_data.astype('float64')
test_targets = test_targets.astype('float64')

In [78]:
print(train_data[0:10])

[[ 86. 133.  26.   8.   4.]
 [ 13. 133.  26.   9.   4.]
 [ 13. 133.  26.  10.   4.]
 [115. 133.  26.  13.   4.]
 [115. 133.  26.  14.   4.]
 [227. 133.  26.  15.   4.]
 [ -1. 133.  27.   2.   4.]
 [241. 133.  27.   3.   4.]
 [249. 133.  27.   8.   4.]
 [ 34. 133.  27.   9.   4.]]


It would be problematic to feed into a neural network values that all take wildly different ranges. The network might be able to automatically adapt to such heterogeneous data, but it would definitely make learning more difficult. A widespread best practice to deal with such data is to do feature-wise normalization: for each feature in the input data (a column in the input data matrix), we will subtract the mean of the feature and divide by the standard deviation, so that the feature will be centered around 0 and will have a unit standard deviation. This is easily done in Numpy or by using a scikit scaler:

mean = train_data.mean(axis=0)
train_data -= mean
std = train_data.std(axis=0)
train_data /= std

test_data -= mean
test_data /= std

In [79]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler

train_data = RobustScaler().fit_transform(train_data)
test_data = RobustScaler().fit_transform(test_data)


In [80]:
train_data[0:10]

array([[-0.20394737,  1.56060606, -0.11538462, -0.14285714,  0.        ],
       [-0.68421053,  1.56060606, -0.11538462,  0.        ,  0.        ],
       [-0.68421053,  1.56060606, -0.11538462,  0.14285714,  0.        ],
       [-0.01315789,  1.56060606, -0.11538462,  0.57142857,  0.        ],
       [-0.01315789,  1.56060606, -0.11538462,  0.71428571,  0.        ],
       [ 0.72368421,  1.56060606, -0.11538462,  0.85714286,  0.        ],
       [-0.77631579,  1.56060606, -0.07692308, -1.        ,  0.        ],
       [ 0.81578947,  1.56060606, -0.07692308, -0.85714286,  0.        ],
       [ 0.86842105,  1.56060606, -0.07692308, -0.14285714,  0.        ],
       [-0.54605263,  1.56060606, -0.07692308,  0.        ,  0.        ]])

In [81]:
test_data[0:10]

array([[ 0.20529801, -0.18181818, -0.40740741, -0.28571429,  0.        ],
       [-0.66887417, -0.25757576,  0.18518519,  0.14285714,  0.        ],
       [ 0.77483444, -0.25757576,  0.81481481, -0.28571429,  0.        ],
       [-0.78145695,  0.34848485,  0.88888889, -0.42857143,  0.        ],
       [ 0.81456954, -0.1969697 , -0.18518519, -0.57142857,  0.        ],
       [-0.00662252,  0.71212121, -0.96296296,  0.14285714,  0.        ],
       [-0.78145695,  1.1969697 , -1.        , -0.42857143,  0.        ],
       [ 0.68874172, -0.16666667, -0.44444444,  0.28571429,  0.        ],
       [-0.22516556,  1.25757576,  0.25925926,  0.71428571,  0.        ],
       [ 0.29801325, -0.04545455,  0.66666667,  0.85714286,  0.        ]])

In [82]:
from keras import models
from keras import layers


/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [83]:

def build_model():

    # start with an empty model
    model = models.Sequential()
    
    # add a first layer with 64 neurons/outputs
    model.add(layers.Dense(64, activation='relu',
                           input_shape=(train_data.shape[1],)))
    
    # add a second layer, also with 64 nodes/outputs
    model.add(layers.Dense(64, activation='relu'))
    
    # add a final layer without any activation function!  
    # Just let the floating point value come out directly without being adjusted
    model.add(layers.Dense(1))
    
    # standard compile options for a regression problem
    model.compile(optimizer='rmsprop', loss='mse', metrics=['mae'])
    
    # return the model so it can be trained
    return model

In [84]:
model = build_model()
print('training model')
model.fit(train_data,train_targets,epochs=10, batch_size=1, verbose=1)
print('evaluating model fit:')
val_mse, val_mae = model.evaluate(test_data, test_targets, verbose=0)
print(val_mse,val_mae)

training model
Epoch 1/10
35510/35510 [==============================] - 24s 677us/step - loss: 1072.7123 - mean_absolute_error: 16.7278
Epoch 2/10
35510/35510 [==============================] - 24s 686us/step - loss: 368.7849 - mean_absolute_error: 11.4031
Epoch 3/10
35510/35510 [==============================] - 26s 724us/step - loss: 357.1972 - mean_absolute_error: 11.2664
Epoch 4/10
35510/35510 [==============================] - 26s 724us/step - loss: 346.5462 - mean_absolute_error: 11.1693
Epoch 5/10
35510/35510 [==============================] - 26s 725us/step - loss: 338.6795 - mean_absolute_error: 11.0711
Epoch 6/10
35510/35510 [==============================] - 27s 753us/step - loss: 334.3073 - mean_absolute_error: 11.0026
Epoch 7/10
35510/35510 [==============================] - 26s 728us/step - loss: 329.5138 - mean_absolute_error: 10.9072
Epoch 8/10
35510/35510 [==============================] - 27s 764us/step - loss: 326.9153 - mean_absolute_error: 10.9200
Epoch 9/10
35510

In [91]:
train_data[0:10]

array([[-0.20394737,  1.56060606, -0.11538462, -0.14285714,  0.        ],
       [-0.68421053,  1.56060606, -0.11538462,  0.        ,  0.        ],
       [-0.68421053,  1.56060606, -0.11538462,  0.14285714,  0.        ],
       [-0.01315789,  1.56060606, -0.11538462,  0.57142857,  0.        ],
       [-0.01315789,  1.56060606, -0.11538462,  0.71428571,  0.        ],
       [ 0.72368421,  1.56060606, -0.11538462,  0.85714286,  0.        ],
       [-0.77631579,  1.56060606, -0.07692308, -1.        ,  0.        ],
       [ 0.81578947,  1.56060606, -0.07692308, -0.85714286,  0.        ],
       [ 0.86842105,  1.56060606, -0.07692308, -0.14285714,  0.        ],
       [-0.54605263,  1.56060606, -0.07692308,  0.        ,  0.        ]])

In [90]:
train_targets[0:15]

array([364., 359., 366., 367., 368., 360., 349., 328., 392., 340., 341.,
       336., 308., 359., 386.])

In [92]:
test_data[0:10]

array([[ 0.20529801, -0.18181818, -0.40740741, -0.28571429,  0.        ],
       [-0.66887417, -0.25757576,  0.18518519,  0.14285714,  0.        ],
       [ 0.77483444, -0.25757576,  0.81481481, -0.28571429,  0.        ],
       [-0.78145695,  0.34848485,  0.88888889, -0.42857143,  0.        ],
       [ 0.81456954, -0.1969697 , -0.18518519, -0.57142857,  0.        ],
       [-0.00662252,  0.71212121, -0.96296296,  0.14285714,  0.        ],
       [-0.78145695,  1.1969697 , -1.        , -0.42857143,  0.        ],
       [ 0.68874172, -0.16666667, -0.44444444,  0.28571429,  0.        ],
       [-0.22516556,  1.25757576,  0.25925926,  0.71428571,  0.        ],
       [ 0.29801325, -0.04545455,  0.66666667,  0.85714286,  0.        ]])

In [89]:
test_targets[0:15]

array([314.,  13.,  15.,  11.,  14., 179.,  18., 316.,  16., 267.,  26.,
        11.,  12.,  12.,  10.])